name: Deploy my lambda function

on:
 push:
  branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Check out code
       uses: actions/checkout@v2
     - name: Setup python
       uses: actions/setup-python@v2
       with:
         python-version: 3.8
     - name: Install libraries
       run: |
            cd function
            python -m pip install --upgrade pip
            if [ -f requirement.txt ]; then pip install -r requirements.txt -t .; fi
     - name: Create zip bundle
       run: |
            cd function
            zip -r ../${{ github.sha }}.zip .
     - name: Archive the artifact
       uses: actions/upload-artifact@v4
       with:
         name: zipped-bundle
         path: ${{ github.sha }}.zip

  upload:
     runs-on: ubuntu-latest
     needs: build
     steps:
     - name: Download-artifact
       uses: actions/download-artifact@v4.1.4
       with:
         name: zipped-bundle
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v4
       with: 
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
     - name: upload the s3
       run: |
         aws s3 cp ${{ github.sha }}.zip s3://myhjui23/${{ github.sha }}.zip

  deploy:
     runs-on: ubuntu-latest
     needs: upload
     steps: 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with: 
           aws-region: us-east-1
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
       - name: upload function
         run: 
           aws lambda update-function-code --function-name My-Lambda-Function --s3-bucket myhjui23 --s3-key ${{ github.sha }}.zip --publish 
        
                
          
